In [2]:
import polars as pl
from datetime import date

In [3]:
sales = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\E-Commerce-Sales-Customer-Analytics\data\raw\Sales.csv")

In [4]:
sales.glimpse()

Rows: 62884
Columns: 9
$ Order Number  <i64> 366000, 366001, 366001, 366002, 366002, 366002, 366004, 366004, 366005, 366007
$ Line Item     <i64> 1, 1, 2, 1, 2, 3, 1, 2, 1, 1
$ Order Date    <str> '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016'
$ Delivery Date <str> null, '1/13/2016', '1/13/2016', '1/12/2016', '1/12/2016', '1/12/2016', null, null, null, null
$ CustomerKey   <i64> 265598, 1269051, 1269051, 266019, 266019, 266019, 1107461, 1107461, 844003, 2035771
$ StoreKey      <i64> 10, 0, 0, 0, 0, 0, 38, 38, 33, 43
$ ProductKey    <i64> 1304, 1048, 2007, 1106, 373, 1080, 163, 1529, 421, 1617
$ Quantity      <i64> 1, 2, 1, 7, 1, 4, 6, 2, 4, 1
$ Currency Code <str> 'CAD', 'USD', 'USD', 'CAD', 'CAD', 'CAD', 'GBP', 'GBP', 'EUR', 'USD'

In [5]:
sales.null_count()

shape: (1, 9)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬────────────┬──────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ StoreKey ┆ ProductKey ┆ Quantity ┆ Currency Code │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ---           │
│ u32          ┆ u32       ┆ u32        ┆ u32           ┆   ┆ u32      ┆ u32        ┆ u32      ┆ u32           │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪════════════╪══════════╪═══════════════╡
│ 0            ┆ 0         ┆ 0          ┆ 49719         ┆ … ┆ 0        ┆ 0          ┆ 0        ┆ 0             │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴────────────┴──────────┴───────────────┘

In [6]:
sales.head(20)

shape: (20, 9)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬────────────┬──────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ StoreKey ┆ ProductKey ┆ Quantity ┆ Currency Code │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ---           │
│ i64          ┆ i64       ┆ str        ┆ str           ┆   ┆ i64      ┆ i64        ┆ i64      ┆ str           │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪════════════╪══════════╪═══════════════╡
│ 366000       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 10       ┆ 1304       ┆ 1        ┆ CAD           │
│ 366001       ┆ 1         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 1048       ┆ 2        ┆ USD           │
│ 366001       ┆ 2         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 2007       ┆ 1        ┆ USD           │
│ 366002       ┆ 1         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 1106       ┆ 7        ┆ CAD           │
│ 366002       ┆ 2         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 373        ┆ 1        ┆ CAD           │
│ …            ┆ …         ┆ …          ┆ …             ┆ … ┆ …        ┆ …          ┆ …        ┆ …             │
│ 366010       ┆ 1         ┆ 1/1/2016   ┆ 1/8/2016      ┆ … ┆ 0        ┆ 618        ┆ 5        ┆ CAD           │
│ 366011       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 128        ┆ 7        ┆ USD           │
│ 366011       ┆ 2         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1638       ┆ 1        ┆ USD           │
│ 366011       ┆ 3         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1634       ┆ 1        ┆ USD           │
│ 366011       ┆ 4         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 2392       ┆ 3        ┆ USD           │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴────────────┴──────────┴───────────────┘

In [29]:
sales.with_columns(
    pl.col("Order Date").str.to_datetime(format = "m%/d%/Y%")
)

InvalidOperationError: conversion from `str` to `datetime[μs]` failed in column 'Order Date' for 1020 out of 1020 values: ["2/16/2017", "2/16/2017", … "2/17/2017"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string

This error occurred in the following expression:
	col("Order Date").str.strptime(["raise"])

In [9]:
stores = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\E-Commerce-Sales-Customer-Analytics\data\raw\Stores.csv")
stores

shape: (67, 5)
┌──────────┬───────────────┬──────────────────────────────┬───────────────┬───────────┐
│ StoreKey ┆ Country       ┆ State                        ┆ Square Meters ┆ Open Date │
│ ---      ┆ ---           ┆ ---                          ┆ ---           ┆ ---       │
│ i64      ┆ str           ┆ str                          ┆ i64           ┆ str       │
╞══════════╪═══════════════╪══════════════════════════════╪═══════════════╪═══════════╡
│ 1        ┆ Australia     ┆ Australian Capital Territory ┆ 595           ┆ 1/1/2008  │
│ 2        ┆ Australia     ┆ Northern Territory           ┆ 665           ┆ 1/12/2008 │
│ 3        ┆ Australia     ┆ South Australia              ┆ 2000          ┆ 1/7/2012  │
│ 4        ┆ Australia     ┆ Tasmania                     ┆ 2000          ┆ 1/1/2010  │
│ 5        ┆ Australia     ┆ Victoria                     ┆ 2000          ┆ 12/9/2015 │
│ …        ┆ …             ┆ …                            ┆ …             ┆ …         │
│ 63       ┆ United States ┆ Utah                         ┆ 2000          ┆ 3/6/2008  │
│ 64       ┆ United States ┆ Washington DC                ┆ 1330          ┆ 1/1/2010  │
│ 65       ┆ United States ┆ West Virginia                ┆ 1785          ┆ 1/1/2012  │
│ 66       ┆ United States ┆ Wyoming                      ┆ 840           ┆ 1/1/2014  │
│ 0        ┆ Online        ┆ Online                       ┆ null          ┆ 1/1/2010  │
└──────────┴───────────────┴──────────────────────────────┴───────────────┴───────────┘

In [10]:
stores.null_count()

shape: (1, 5)
┌──────────┬─────────┬───────┬───────────────┬───────────┐
│ StoreKey ┆ Country ┆ State ┆ Square Meters ┆ Open Date │
│ ---      ┆ ---     ┆ ---   ┆ ---           ┆ ---       │
│ u32      ┆ u32     ┆ u32   ┆ u32           ┆ u32       │
╞══════════╪═════════╪═══════╪═══════════════╪═══════════╡
│ 0        ┆ 0       ┆ 0     ┆ 1             ┆ 0         │
└──────────┴─────────┴───────┴───────────────┴───────────┘