In [1]:
import polars as pl
import datetime

In [19]:
sales = pl.read_csv(r"C:\Users\LENOVO\Desktop\Data Analitika\E-Commerce-Sales-Customer-Analytics\data\raw\Sales.csv")

In [20]:
sales.glimpse()

Rows: 62884
Columns: 9
$ Order Number  <i64> 366000, 366001, 366001, 366002, 366002, 366002, 366004, 366004, 366005, 366007
$ Line Item     <i64> 1, 1, 2, 1, 2, 3, 1, 2, 1, 1
$ Order Date    <str> '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016', '1/1/2016'
$ Delivery Date <str> null, '1/13/2016', '1/13/2016', '1/12/2016', '1/12/2016', '1/12/2016', null, null, null, null
$ CustomerKey   <i64> 265598, 1269051, 1269051, 266019, 266019, 266019, 1107461, 1107461, 844003, 2035771
$ StoreKey      <i64> 10, 0, 0, 0, 0, 0, 38, 38, 33, 43
$ ProductKey    <i64> 1304, 1048, 2007, 1106, 373, 1080, 163, 1529, 421, 1617
$ Quantity      <i64> 1, 2, 1, 7, 1, 4, 6, 2, 4, 1
$ Currency Code <str> 'CAD', 'USD', 'USD', 'CAD', 'CAD', 'CAD', 'GBP', 'GBP', 'EUR', 'USD'

In [21]:
sales.null_count()

shape: (1, 9)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬────────────┬──────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ StoreKey ┆ ProductKey ┆ Quantity ┆ Currency Code │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ---           │
│ u32          ┆ u32       ┆ u32        ┆ u32           ┆   ┆ u32      ┆ u32        ┆ u32      ┆ u32           │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪════════════╪══════════╪═══════════════╡
│ 0            ┆ 0         ┆ 0          ┆ 49719         ┆ … ┆ 0        ┆ 0          ┆ 0        ┆ 0             │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴────────────┴──────────┴───────────────┘

In [22]:
sales.head(20)

shape: (20, 9)
┌──────────────┬───────────┬────────────┬───────────────┬───┬──────────┬────────────┬──────────┬───────────────┐
│ Order Number ┆ Line Item ┆ Order Date ┆ Delivery Date ┆ … ┆ StoreKey ┆ ProductKey ┆ Quantity ┆ Currency Code │
│ ---          ┆ ---       ┆ ---        ┆ ---           ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ---           │
│ i64          ┆ i64       ┆ str        ┆ str           ┆   ┆ i64      ┆ i64        ┆ i64      ┆ str           │
╞══════════════╪═══════════╪════════════╪═══════════════╪═══╪══════════╪════════════╪══════════╪═══════════════╡
│ 366000       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 10       ┆ 1304       ┆ 1        ┆ CAD           │
│ 366001       ┆ 1         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 1048       ┆ 2        ┆ USD           │
│ 366001       ┆ 2         ┆ 1/1/2016   ┆ 1/13/2016     ┆ … ┆ 0        ┆ 2007       ┆ 1        ┆ USD           │
│ 366002       ┆ 1         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 1106       ┆ 7        ┆ CAD           │
│ 366002       ┆ 2         ┆ 1/1/2016   ┆ 1/12/2016     ┆ … ┆ 0        ┆ 373        ┆ 1        ┆ CAD           │
│ …            ┆ …         ┆ …          ┆ …             ┆ … ┆ …        ┆ …          ┆ …        ┆ …             │
│ 366010       ┆ 1         ┆ 1/1/2016   ┆ 1/8/2016      ┆ … ┆ 0        ┆ 618        ┆ 5        ┆ CAD           │
│ 366011       ┆ 1         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 128        ┆ 7        ┆ USD           │
│ 366011       ┆ 2         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1638       ┆ 1        ┆ USD           │
│ 366011       ┆ 3         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 1634       ┆ 1        ┆ USD           │
│ 366011       ┆ 4         ┆ 1/1/2016   ┆ null          ┆ … ┆ 66       ┆ 2392       ┆ 3        ┆ USD           │
└──────────────┴───────────┴────────────┴───────────────┴───┴──────────┴────────────┴──────────┴───────────────┘